import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-xs min-w-80 ml-auto mr-auto bg-figma-canvas-black flex h-screen justify-center items-center">
        {children}
      </body>
    </html>
  );
}
